# ==========================================
# Cradio 左手（Central）专属配置
# ==========================================

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# ZMK Studio 仅在主控端（左手）开启
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# USB 日志（调试时取消注释）
# CONFIG_ZMK_USB_LOGGING=y
