# ==========================================
# Cradio 左手（Central）专属配置
# ==========================================

# ZMK Studio 仅在主控端（左手）开启
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_IDLE_TIMEOUT_SEC=300

# USB 日志（调试时取消注释）
# CONFIG_ZMK_USB_LOGGING=y
